---
exclude: [bundle]
defaults:
   - 
    scope:
     path: ""
     type: pages
    values: 
     layout: lamalayout
     title: TiMBL
     author: Ko van der sloot, Antal van den Bosch, Walter Daelemans, Peter Berck, Maarten van Gompel, Ton Weijters, Jakub Zavrel
     keywords: memory-based classifier, kNN, IGtree, machine learning
     description: Timbl is a memory-based classifier
     lang: en
     menu: 
      - label: Home
        url: https://languagemachines.github.io/timbl/
      - label: Source
        url: https://github.com/LanguageMachines/timbl/
      - label: Releases
        url: https://github.com/LanguageMachines/timbl/releases/
---
